serverAddr = "160.250.204.220"
serverPort = 7000

[auth]
method = "token"
token = "long-strong-random-token" 

[[proxies]]
name = "ssh"        
type = "tcp"               
localIP = "127.0.0.1"      
localPort = 22             
remotePort = 50022          

[[proxies]]
name = "jellyfin"        
type = "tcp"               
localIP = "127.0.0.1"      
localPort = 8096             
remotePort = 58096

# Example: TCP port range mapping (client ports 8000-8005 map to server ports 9000-9005)
# [[proxies]]
# name = "port_range_example"
# type = "tcp"
# localIP = "127.0.0.1"
# localPort = "8000-8005" # Local port range
# remotePort = "9000-9005" # Remote port range
