services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:1000" 
    ports:
      - "5555:8080" 
    environment:
      FB_PORT: 8080
      ADMIN_PASS: "password"
    volumes:
      - ../shared_dir:/srv:U
      - ./db:/database/:U
      - ./config:/config:U
    security_opt:
      - no-new-privileges:true 
    cap_drop:
      - ALL    
    cap_add:
      - CHOWN
      - SETUID
      - SETGID


networks:
  podman:
    external: true
