version: "3.9"

services:
  db:
    image: docker.io/library/postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gitea
    networks:
      - gtnet
    volumes:
      - ./postgres:/var/lib/postgresql/data

  server:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=postgres
      - GITEA__server__ROOT_URL=https://domain_name.tld/
    restart: always
    networks:
      - gtnet
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:22"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: gitea_nginx
    volumes:
      - ./tls:/etc/nginx/tls:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    restart: always
    networks:
      - gtnet
    depends_on:
      - db
      - server

networks:
  gtnet:
    external: false
