
services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./lists/blocklist.conf:/etc/blocklist.conf
      - ./lists/peterlowe.conf:/etc/peterlowe.conf
      - ./lists/peterlowev6.conf:/etc/peterlowev6.conf
      - ./lists/proplus.conf:/etc/proplus.conf
      - ./log/dnsmasq.log:/var/log/dnsmasq.log
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    privileged: true
    restart: always

networks:
  podman:
    external: true

