version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
      - "7359:7359/udp"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: ./jellyfin/media
        target: /media
    restart: 'unless-stopped'

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_PASSWORD: ncpass
    volumes:
      - ./nextcloud/db/:/var/lib/mysql
    networks:
      - ncnet

  app:
    build: ./nextcloud/
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_PASSWORD: ncpass
    volumes:
      - ./nextcloud/cloud/:/var/www/html
      - ./nextcloud/config/:/var/www/html/config
    depends_on:
      - db
    networks:
      - ncnet

networks:
  ncnet:
    driver: bridge
