services:
  windows:
    image: docker.io/dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      DISK_SIZE: "64G"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      USERNAME: "rexdy"
      PASSWORD: "password"
      LANGUAGE: "English"
      REGION: "en-IN"
      KEYBOARD: "en-IN"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./storage:/storage:Z
      - ../shared_dir:/shared
    restart: always
    stop_grace_period: 2m

networks:
  podman:
    external: true
