version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
      - "7359:7359/udp"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ./jellyfin/media
        target: /media
    restart: 'unless-stopped'

networks:
  podman_default:
    external: true
