version: '3.9'

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_PASSWORD: ncpass
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - ncnet

  app:
    image: nextcloud:28-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_PASSWORD: ncpass
    volumes:
      - ./data:/var/www/html
      - ./config:/var/www/html/config
    depends_on:
      - db
    networks:
      - ncnet

networks:
  ncnet:
    driver: bridge

