services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_PASSWORD: ncpass
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - ncnet

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_PASSWORD: ncpass
    volumes:
      - /home/nas/cloud:/var/www/html
      - ./config:/var/www/html/config
    depends_on:
      - db
    networks:
      - ncnet

networks:
  ncnet:
    driver: bridge
